// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type TradeData struct {
	Symbol    string    `json:"symbol"`
	LastPrice int       `json:"last_price"`
	Volume    int       `json:"volume"`
	High      int       `json:"high"`
	Low       int       `json:"low"`
	Timestamp time.Time `json:"timestamp"`
}
